version: '{build}'

skip_tags: true

install: []

image:
  - Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "Visual Studio 14 2015" -A x64 ..
  - if "%PLATFORM%"=="Win32" cmake -G "Visual Studio 14 2015" -A Win32 ..
  - cmake --build .
